name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Rustup
        run: rustup component add clippy rustfmt
      - name: Rustfmt
        run: cargo fmt -- --check
      - name: Clippy
        run: cargo clippy -- -D warnings
      - name: Build
        run: |
          cargo build --no-default-features --verbose
          cargo build --all-features --verbose
      - name: Run tests
        run: |
          cargo test --no-default-features --verbose
          cargo test --all-features --all-targets --verbose
